Proyecto2024/urls.py
from django.contrib import admin
from django.urls import path
#Codigo Agregado Daniel 
from accounts import views
#from accounts import registrar_estudiante
#Codigo Agregado Christian 
from django.urls import include

urlpatterns = [
    #Codigo Christian 
    path('admin/', admin.site.urls),
    #Añadido
    #path('accounts/', include('django.contrib.auth.urls')),
    path('', include('accounts.urls')),
    

]   

accounts/urls.py
from django.urls import path
#from django.contrib import admin
from . import views
from .views import registrar_estudiante, listar_estudiantes, editar_estudiante

urlpatterns = [
    #Codio Login - Codigo Chritian
    path('accounts/login/', views.login_view, name='login'),
    path('', views.home, name='home'),
    path('accounts/logout/',views.exit,name='exit'),
    path('accounts/profile/',views.profile,name='profile'),
    path('listar-estudiantes/',views.listar_estudiantes,name='listar_estudiantes'),
    path('registrar-estudiantes/',views.registrar_estudiante,name='registrar_estudiante'),
    path('editar-estudiantes/<int:id>/',views.editar_estudiante,name='editar_estudiante'),
    path('eliminar_estudiante/<int:id>/', views.eliminar_estudiante, name='eliminar_estudiante'),


   
    path('listar-docentes/',views.listar_docentes,name='listardocentes'),
    #Codigo Menu administrador - Agregado por Daniel 
    
    
    path('registrodocente/', views.registrodocente, name='registrodocente'),
    #path('visualizardatosregistros/', views.visualizarregistro, name='visualizarregistro'),
    #Codigo Asignacion Docente - Daniel 
    path('administrarasignaciondocente/', views.administrarasignaciondocente, name='administrarasignaciondocente'),
    path('eliminarasignacion/<int:id>/', views.eliminarasignacion, name='eliminarasignacion'),
    path('editarasignacion/<int:id>/', views.editarasignacion, name='editarasignacion'),
    path('visualizarasignaciondocente/', views.visualizarasignaciondocente, name='visualizarasignaciondocente'),
    
    #Codigo Registro de Asistencia - Ricardo
    path('asistencia/gestion_asistencia/', views.gestionar_asistencia, name='gestionar_asistencia'),
    path('asistencia/registro_asistencia/<int:id_gradoseccion>/<str:fecha>/', views.registrar_asistencia, name='registrar_asistencia'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django import template
from django.core.validators import RegexValidator

# Create your models here.
register = template.Library()

@register.filter(name='has_group') 
def has_group(user, group_name):
    user.groups.filter(name=group_name).exists()
    return  

#Codigo Agreado Christian 
class Docente(models.Model):
    GENERO_CHOICES = [
        ('M', 'Masculino'),
        ('F', 'Femenino'),
    ]
    user = models.OneToOneField(User, on_delete= models.CASCADE )
    dui= models.CharField(primary_key=True, max_length=9, null = False, unique= True)
    nombreDocente = models.CharField(max_length=100, null= False)
    apellidoDocente = models.CharField(max_length=100, null= False)
    generoDocente = models.CharField(max_length=1, null= False, choices=GENERO_CHOICES)
    direccionDocente = models.CharField(max_length=100, null = False)
    correoDocente = models.EmailField(unique= True, null = False )
    fechaRegistroDocente = models.DateField(auto_now_add=True, null=False)
    edadDocente = models.IntegerField(null=False)
    telefonoDocente = models.CharField(max_length = 8, validators=[RegexValidator(r'^\d{8}$', 'Ingrese un número de teléfono válido de 8 dígitos.')] ,null = False)


    def __str__(self):
        return f"{self.nombreDocente}   {self.apellidoDocente}"


class Grado(models.Model):
    idGrado = models.AutoField(primary_key=True, unique=True, null=False)
    nombreGrado = models.CharField(max_length=25)

    def __str__(self):
        return self.nombreGrado


class Seccion(models.Model):
    idSeccion = models.AutoField(primary_key=True)
    nombreSeccion = models.CharField(max_length=100)

    def __str__(self):
        return self.nombreSeccion

class GradoSeccion(models.Model):
    id_gradoseccion = models.AutoField(primary_key=True, unique=True, null=False)
    grado = models.ForeignKey(Grado, on_delete=models.CASCADE, related_name='grado_secciones')
    seccion = models.ForeignKey(Seccion, on_delete=models.CASCADE, related_name='grado_secciones')

    class Meta:
        unique_together = ('grado', 'seccion')

    def __str__(self):
        return f"{self.grado.nombreGrado} - {self.seccion.nombreSeccion}"




class Estudiante(models.Model):
    
  
    user = models.OneToOneField(User, on_delete= models.CASCADE )
    id_alumno = models.AutoField(primary_key= True, unique= True, null= False)
    nombreAlumno = models.CharField(max_length = 100, null= False)
    apellidoAlumno = models.CharField(max_length = 100, null= False)
    edadAlumno = models.IntegerField(null=False)
    id_gradoseccion = models.ForeignKey(GradoSeccion, on_delete=models.RESTRICT)
    numeroTelefonoAlumno = models.CharField(max_length = 8, null = False)
    fechaRegistroAlumno = models.DateField(auto_now_add=True, null=False)
    nombreResponsable = models.CharField(max_length = 100, null= False)
    apellidoResposable = models.CharField(max_length = 100, null= False)
    numeroTelefonoResposable = models.CharField(max_length = 8, null = False)
    duiResponsable= models.CharField( max_length=9, null = False, unique= True)
    direccionResponsable = models.CharField(max_length=100, null = False)
    edadResponsable = models.IntegerField(null=False) 


    def __str__(self):
        return f"{self.nombreAlumno} d{self.apellidoAlumno}"      


class Asignacion(models.Model):
    docente = models.ForeignKey(Docente, on_delete=models.CASCADE, related_name='asignaciones')
    grado_seccion = models.ForeignKey(GradoSeccion, on_delete=models.CASCADE, related_name='asignaciones')

    def __str__(self):
        return f"{self.docente.nombreDocente} - {self.grado_seccion.grado.nombreGrado} - {self.grado_seccion.seccion.nombreSeccion}"

#segundo sprint
class TipoActividad(models.Model):
    id_tipoactividad = models.AutoField(primary_key=True, unique=True, null=False)
    nombretipoactividad = models.CharField(max_length=100)

class Materia(models.Model):
    id_materia = models.AutoField(primary_key=True)
    nombre_materia = models.CharField(max_length=25)
    anio_materia = models.IntegerField()

class MateriaGradoSeccion(models.Model):
    id_matrgrasec = models.AutoField(primary_key=True, unique=True, null=False)
    id_materia = models.ForeignKey(Materia, on_delete=models.RESTRICT, null=True)
    id_gradoseccion = models.ForeignKey(GradoSeccion, on_delete=models.RESTRICT, null=True)


class DocenteMateriaGrado(models.Model):
    id_doc_mat_grado = models.AutoField(primary_key=True, unique=True, null=False)
    dui = models.ForeignKey(Docente, on_delete=models.RESTRICT, null=True)
    id_matrgrasec = models.ForeignKey(MateriaGradoSeccion, on_delete=models.RESTRICT)


class Asistencia(models.Model):
    id_asistencia = models.AutoField(primary_key=True, unique=True, null=False)
    id_alumno = models.ForeignKey(Estudiante, on_delete=models.RESTRICT)
    idgradoseccion = models.ForeignKey(GradoSeccion, on_delete=models.RESTRICT)
    fechaasistencia = models.DateField()
    asistio = models.CharField(max_length=1)

class Conducta(models.Model):
    id_conducta = models.AutoField(primary_key=True, unique=True, null=False)
    id_alumno = models.ForeignKey(Estudiante, on_delete=models.RESTRICT)
    fecha_conducta = models.CharField(max_length=15)
    obsevacion_conducta = models.CharField(max_length=250)
    nota_conducta = models.FloatField()

class ActividadAcademica(models.Model):
    id_actividad = models.AutoField(primary_key=True, unique=True, null=False)
    id_tipoactividad = models.ForeignKey(TipoActividad, on_delete=models.RESTRICT, unique=True, null=False)
    id_alumno = models.ForeignKey(Estudiante, on_delete=models.RESTRICT)
    id_matrgrasec = models.ForeignKey(MateriaGradoSeccion, on_delete=models.RESTRICT)
    nombre_actividad = models.CharField(max_length=25)
    descripcion_actividad = models.CharField(max_length=50)
    fecha_actividad = models.DateField()
    nota = models.FloatField()

#Codigo para Horarios de Clases 
class HorarioClase(models.Model):
    docente_materia_grado = models.ForeignKey(DocenteMateriaGrado, on_delete=models.CASCADE, null=True)  # Ahora permite valores nulos
    dia_semana = models.CharField(max_length=9, choices=[
        ('Lunes', 'Lunes'), 
        ('Martes', 'Martes'),
        ('Miércoles', 'Miércoles'), 
        ('Jueves', 'Jueves'),
        ('Viernes', 'Viernes'),
        ('Sábado', 'Sábado'),
        ('Domingo', 'Domingo'),
    ])
    hora_inicio = models.TimeField()
    hora_fin = models.TimeField()

    class Meta:
        unique_together = ('docente_materia_grado', 'dia_semana', 'hora_inicio', 'hora_fin')

    def __str__(self):
        return f"{self.docente_materia_grado} ({self.dia_semana}, {self.hora_inicio} - {self.hora_fin})"

accounts/forms.py
from django import forms
from django.forms.models import modelformset_factory


#Codigo Daniel 
from .models import Asignacion, Docente, GradoSeccion, Estudiante, Asistencia
from django.contrib.auth.models import User

#Codigo Christian 
from django.contrib.auth.forms import AuthenticationForm
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
#Codigo Daniel 
class AsignacionForm(forms.ModelForm):
    class Meta:
        model = Asignacion
        fields = ['docente', 'grado_seccion']
        widgets = {
            'docente' : forms.Select(attrs={'class':'select-form'}),
            'grado_seccion' : forms.Select(attrs={'class':'select-form'}),
        }

class EstudianteForm(forms.ModelForm):

    class Meta:
        model = Estudiante
        fields = [
            'nombreAlumno', 'apellidoAlumno', 'id_gradoseccion', 'edadAlumno', 'numeroTelefonoAlumno',
            'nombreResponsable', 'apellidoResposable', 'numeroTelefonoResposable',
            'duiResponsable', 'direccionResponsable', 'edadResponsable'
        ]
        widgets = {
            'nombreAlumno': forms.TextInput(attrs={'placeholder': 'Ingrese el nombre'}),
            'apellidoAlumno': forms.TextInput(attrs={'placeholder': 'Ingrese el apellido'}),
            'id_gradoseccion': forms.Select(),
            'edadAlumno': forms.NumberInput(attrs={'placeholder': 'Ingrese la edad'}),
            'numeroTelefonoAlumno': forms.TextInput(attrs={'placeholder': 'Ingrese el número de teléfono', 'pattern': r'^\d{8}$'}),
            'nombreResponsable': forms.TextInput(attrs={'placeholder': 'Ingrese el nombre'}),
            'apellidoResposable': forms.TextInput(attrs={'placeholder': 'Ingrese el apellido'}),
            'numeroTelefonoResposable': forms.TextInput(attrs={'placeholder': 'Ingrese el número de teléfono', 'pattern': r'^\d{8}$'}),
            'duiResponsable': forms.TextInput(attrs={'placeholder': 'Ingrese el DUI', 'pattern': r'^\d{9}$'}),
            'direccionResponsable': forms.Textarea(attrs={'placeholder': 'Ingrese la dirección'}),
            'edadResponsable': forms.NumberInput(attrs={'placeholder': 'Ingrese la edad'}),
        }

    def __init__(self, *args, **kwargs):
        super(EstudianteForm, self).__init__(*args, **kwargs)
        if self.errors:
            self.is_validated = True
        else:
            self.is_validated = False
        for field_name, field in self.fields.items():
            if self.errors.get(field_name):
                field.widget.attrs.update({'class': 'form-control is-invalid'})
            else:
                field.widget.attrs.update({'class': 'form-control'})

    def clean_edadAlumno(self):
        edadAlumno = self.cleaned_data.get('edadAlumno')
        if edadAlumno <= 0:
            raise forms.ValidationError('La edad debe ser mayor que cero')
        return edadAlumno

    def clean_edadResponsable(self):
        edadResponsable = self.cleaned_data.get('edadResponsable')
        if edadResponsable <= 0:
            raise forms.ValidationError('La edad debe ser mayor que cero')
        return edadResponsable

    def clean_duiResponsable(self):
        duiResponsable = self.cleaned_data.get('duiResponsable')
        if len(duiResponsable) != 9 or not duiResponsable.isdigit():
            raise forms.ValidationError('El DUI debe tener exactamente 9 dígitos')
        return duiResponsable

    def clean_numeroTelefonoAlumno(self):
        numeroTelefonoAlumno = self.cleaned_data.get('numeroTelefonoAlumno')
        if len(numeroTelefonoAlumno) != 8 or not numeroTelefonoAlumno.isdigit():
            raise forms.ValidationError('El número de teléfono debe tener exactamente 8 dígitos')
        return numeroTelefonoAlumno

    def clean_numeroTelefonoResposable(self):
        numeroTelefonoResposable = self.cleaned_data.get('numeroTelefonoResposable')
        if len(numeroTelefonoResposable) != 8 or not numeroTelefonoResposable.isdigit():
            raise forms.ValidationError('El número de teléfono debe tener exactamente 8 dígitos')
        return numeroTelefonoResposable

#Codigo Christian 
class LoginForm(AuthenticationForm):
   def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({
            'id_for_label': 'username',
            'id': 'username',
            'name': 'username',
            'placeholder': 'Ingrese Usuario',
            
        })
        
        self.fields['password'].widget.attrs.update({
            'id_for_label': 'password',
            'id': 'password',
            'name': 'password',
            'placeholder': 'contraseña',
        })

class DocenteForm(forms.ModelForm):
    class Meta:
        model = Docente
        fields = ['dui', 
                  'nombreDocente', 
                  'apellidoDocente', 
                  'generoDocente', 
                  'direccionDocente', 
                  'correoDocente', 
                  'edadDocente', 
                  'telefonoDocente' ]
        widgets = {
            'telefonoDocente': forms.TextInput(attrs={'pattern': r'^\d{8}$'}),
            'dui': forms.TextInput(attrs={'pattern': r'^\d{9}$'}),
        }


    def __init__(self, *args, **kwargs):
        super(DocenteForm, self).__init__(*args, **kwargs)
        if self.errors:
            self.is_validated = True
        else:
            self.is_validated = False
        for field_name, field in self.fields.items():
            if self.errors.get(field_name):
                field.widget.attrs.update({'class': 'form-control is-invalid'})
            else:
                field.widget.attrs.update({'class': 'form-control'})

    def clean_dui(self):
        dui = self.cleaned_data.get('dui')
        if len(dui) != 9 or not dui.isdigit():
            raise ValidationError('El DUI debe tener exactamente 9 dígitos.')
        return dui

    def clean_telefonoDocente(self):
        telefono = self.cleaned_data.get('telefonoDocente')
        if len(telefono) != 8 or not telefono.isdigit():
            raise ValidationError('El teléfono debe tener exactamente 8 dígitos.')
        return telefono

    def clean_correoDocente(self):
        correo = self.cleaned_data.get('correoDocente')
        if not correo:
            raise ValidationError('Por favor, ingrese un correo electrónico válido.')
        
        if User.objects.filter(email=correo).exists():
            raise ValidationError('Este correo electrónico ya está registrado. Por favor, ingrese otro.')
        return correo
    

#Registro de asistencia
ASISTENCIA_CHOICES = [
        ('P', 'Presente'),
        ('A', 'Ausente'),
    ]

class SeleccionarGradoSeccionForm(forms.Form):
    grado_seccion = forms.ModelChoiceField(queryset=GradoSeccion.objects.all(), label="Grado y Sección")
    fecha = forms.DateField(widget=forms.SelectDateWidget(), label="Fecha de asistencia")

class AsistenciaForm(forms.ModelForm):
    class Meta:
        model = Asistencia
        fields = ['id_alumno', 'asistio']
        widgets = {
            'asistio': forms.RadioSelect(choices=ASISTENCIA_CHOICES),  # Usamos radio buttons
        }

AsistenciaFormSet = modelformset_factory(Asistencia, form=AsistenciaForm, extra=0)

accounts/templates/accounts/agregar_horario.html
{% extends "accounts/templates/accounts/base.html" %}
{% load form_tags %}

{% block title %}Asignar Horarios de Clases{% endblock %}

{% block content %}
<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-md-5">
            <h1 class="text-center mb-4">Asignar Horario de Clase</h1>
            <form method="post" class="shadow p-4 bg-light rounded">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_docente_materia_grado">Docente y Materia:</label>
                    {{ form.docente_materia_grado|add_class:"form-control" }}
                </div>
                <div class="form-group">
                    <label for="id_dia_semana">Día de la Semana:</label>
                    {{ form.dia_semana|add_class:"form-control" }}
                </div>
                <div class="form-row">
                    <div class="form-group col-md-6">
                        <label for="id_hora_inicio">Hora de Inicio:</label>
                        {{ form.hora_inicio|add_class:"form-control" }}
                    </div>
                    <div class="form-group col-md-6">
                        <label for="id_hora_fin">Hora de Fin:</label>
                        {{ form.hora_fin|add_class:"form-control" }}
                    </div>
                </div>
                <p></p>
                <button type="submit" class="btn btn-primary btn-block">Guardar</button>
            </form>
            <div class="text-center mt-3">
                <a href="{% url 'lista_horarios' %}" class="btn btn-success">Ver Lista de Horarios Asignados</a>
                <a href="{% url 'home' %}" class="btn btn-secondary">Volver al menu principal</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/editar_estudiante.html
{% extends "accounts/templates/accounts/base.html" %}
{% block title %}SABANA PROYECT {% endblock %}


{% block content %}
<div class="container">
    <h1 class="mt-5 text-center">EDITAR ESTUDIANTE </h1>
    <form id="editar-estudiante-form" method="POST" class="mt-4">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Guardar Cambios</button>
        <button type="button" class="btn btn-danger" id="eliminar-estudiante">Eliminar</button>
        <a href="{% url 'listar_estudiantes' %}" class="btn btn-secondary">Volver</a>
    </form>
</div>

{% block scripts %}
<script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
    document.getElementById('eliminar-estudiante').addEventListener('click', function() {
        Swal.fire({
            title: '¿Estás seguro?',
            text: "¡No podrás revertir esto!",
            icon: 'warning',
            showCancelButton: true,
            confirmButtonColor: '#3085d6',
            cancelButtonColor: '#d33',
            confirmButtonText: 'Sí, eliminar',
            cancelButtonText: 'Cancelar'
        }).then((result) => {
            if (result.isConfirmed) {
                fetch("{% url 'eliminar_estudiante' estudiante.id_alumno %}", {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                        'Content-Type': 'application/json'
                    },
                })
                .then(response => response.json())
                .then(data => {
                    if (data.success) {
                        Swal.fire(
                            '¡Eliminado!',
                            data.message,
                            'success'
                        ).then(() => {
                            window.location.href = "{% url 'listar_estudiantes' %}";
                        });
                    } else {
                        Swal.fire(
                            'Error',
                            data.message,
                            'error'
                        );
                    }
                });
            }
        });
    });

    document.getElementById('editar-estudiante-form').addEventListener('submit', function(e) {
        e.preventDefault();
        const form = this;
        const formData = new FormData(form);

        fetch(form.action, {
            method: form.method,
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            },
            body: formData
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                Swal.fire(
                    '¡Guardado!',
                    data.message,
                    'success'
                ).then(() => {
                    window.location.href = "{% url 'listar_estudiantes' %}";
                });
            } else {
                Swal.fire(
                    'Error',
                    data.message,
                    'error'
                );
            }
        });
    });
</script>
{% endblock %}
{% endblock %}

accounts/templates/accounts/registrodocente.html
{% extends "accounts/templates/accounts/base.html" %}
{% block title %} Sabana - Registro de Docentes {% endblock %}

{% block content %}
{% load widget_tweaks %}
{% load static %}


<div class="container mt-5">
    <div class="row justify-content-center">
        <div class="col-12 col-md-6">
            <h2 class="text-center">Registro de Docentes</h2>
            <p class="text-center">Ingresa los datos del Docente.</p>
            <p class="text-center"><span style="color: red;">* Requerido</span></p>
            {% if messages %}
                {% for message in messages %}
                    {% if message.tags == 'success' %}
                        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                            <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
                            <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
                            </symbol>
                        </svg> 
                        <div class="alert alert-success d-flex align-items-center" role="alert">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Success:"><use xlink:href="#check-circle-fill"/></svg>
                            <div>
                                {{ message }}
                            </div>
                        </div>             
                    {% elif message.tags == 'error' %}
                        <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
                            <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
                                <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
                            </symbol>
                        </svg> 
                        <div class="alert alert-warning d-flex align-items-center" role="alert">
                            <svg class="bi flex-shrink-0 me-2" width="24" height="24" role="img" aria-label="Warning:"><use xlink:href="#exclamation-triangle-fill"/></svg>
                            <div>
                                {{ message }}
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
            <form method="post" id="id_form" class="needs-validation {% if form.is_validated %}was-validated{% endif %} " novalidate>
                {% csrf_token %}
                <div class="row mb-3">
                    <div class="col">
                        <label for="id_nombreDocente" class="form-label">Nombres <span style="color: red;">*</span></label>
                        {% render_field form.nombreDocente class="form-control" placeholder="Ingresa el nombre" %}
                        <div class="invalid-feedback">
                            
                                {{ form.nombreDocente.errors }}
                            
                        </div>
                    </div>
                    <div class="col">
                        <label for="id_apellidoDocente" class="form-label">Apellidos <span style="color: red;">*</span></label>
                        {% render_field form.apellidoDocente class="form-control" placeholder="Ingresa los apellidos" %}
                        <div class="invalid-feedback">
                            
                                {{ form.apellidoDocente.errors }}
                            
                        </div>
                    </div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label for="id_dui" class="form-label">DUI <span style="color: red;">*</span></label>
                        {% render_field form.dui class="form-control" placeholder="Ingresa el DUI" data-mask="00000000-0" %}
                        <div class="invalid-feedback">{{ form.dui.errors }}</div>
                    </div>
                    <div class="col">
                        <label for="id_generoDocente" class="form-label">Género <span style="color: red;">*</span></label>
                        {% render_field form.generoDocente class="form-select" %}
                        <div class="invalid-feedback">{{ form.generoDocente.errors }}</div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="id_direccionDocente" class="form-label">Dirección <span style="color: red;">*</span></label>
                    {% render_field form.direccionDocente class="form-control" placeholder="Ingresa la dirección" %}
                    <div class="invalid-feedback">{{ form.direccionDocente.errors }}</div>
                </div>
                <div class="row mb-3">
                    <div class="col">
                        <label for="id_correoDocente" class="form-label">Correo electrónico <span style="color: red;">*</span></label>
                        {% render_field form.correoDocente class="form-control" placeholder="Ingresa el correo" %}
                        <div class="invalid-feedback">{{ form.correoDocente.errors }}</div>
                    </div>
                    <div class="col">
                        <label for="id_edadDocente" class="form-label">Edad <span style="color: red;">* </span></label>
                        {% render_field form.edadDocente class="form-control" placeholder="Ingresa la edad" %}
                        <div class="invalid-feedback">{{ form.edadDocente.errors }}</div>
                    </div>
                </div>
                <div class="mb-3">
                    <label for="id_telefonoDocente" class="form-label">Teléfono <span style="color: red;">*</span></label>
                    {% render_field form.telefonoDocente class="form-control" placeholder="Ingresa el teléfono" data-mask="0000-0000" %}
                    <div class="invalid-feedback">
                        {{ form.telefonoDocente.errors }}
                    </div>
                </div>
                
                    <div class="row">
                      <div class="mb-3">
                        <button type="submit" class="btn btn-success w-100">Registrar Docente</button>
                      </div>
                      <div class="mb-3">
                            <a class="btn btn-outline-dark w-100" href="{% url 'home' %}" role="button">Cancelar</a>
                      </div>
                    </div>
                
            </form>
        </div>
    </div>
</div>
<script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script>
<script type="text/javascript" src="{% static 'js/jquery.mask.min.js' %}"></script>

<script>
    $(document).ready(function() {
        $("#id_form").submit(function(event) {
            $("#id_dui").unmask(); // Elimina la máscara
            $("#id_telefonoDocente").unmask();
        });
    });
</script>

{% endblock %}

{% block scripts %}

{% endblock %}